# changed default 'Fix held items' to true, due to bug
# added Apply_on_global_check, 'Message on cancel hold'
# 'Downgrade in anvil' replaced 'downgrade repairs'

Message on cancel: true
Message on limit: true
Message on disallowed: true
Message on cancel hold: true
Limit Multiples: true
Stop pickup: false
Restore levels: true
Stop repairs: true
Fix spawned items: false
Infinite anvils: false
Fix held items: true
Downgrade in anvil: false

Apply_on_global_check:
  anvil: false
  table: false
  restrictive: true
  
